@echo off
set "PATH=C:\Users\Pudgie\AppData\Local\Programs\Git\cmd;C:\Users\Pudgie\AppData\Local\Programs\Git\mingw64\bin;%PATH%"
echo [1] Checking Git location...
where git
echo [2] Checking Git version...
git --version
echo [3] Checking branch status...
git status
echo [4] Pushing to origin master...
git push -v origin master
echo [6] Done.
pause
